// src/lib/signs.js
const SIGN_RED = '#C8102E', SIGN_BLUE = '#0F4C9A', SIGN_WHITE = '#FFFFFF',
      SIGN_BLACK = '#111111', SIGN_YELLOW = '#F5C400', SIGN_GREEN = '#1E9E4A';

function triDown(fill, stroke){ return `<path d="M6 12 H94 L50 90 Z" fill="${fill}" stroke="${stroke}" stroke-width="10" stroke-linejoin="round"/>`; }
function triUp(inner){ return `<path d="M50 10 L94 88 H6 Z" fill="${SIGN_WHITE}" stroke="${SIGN_RED}" stroke-width="10" stroke-linejoin="round"/>${inner||''}`; }
function circleBlue(inner){ return `<circle cx="50" cy="50" r="46" fill="${SIGN_BLUE}" stroke="${SIGN_WHITE}" stroke-width="4"/>${inner||''}`; }
function circleRed(inner){ return `<circle cx="50" cy="50" r="46" fill="${SIGN_WHITE}" stroke="${SIGN_RED}" stroke-width="10"/>${inner||''}`; }
function rectBlue(inner){ return `<rect x="4" y="4" width="92" height="92" rx="6" fill="${SIGN_BLUE}" stroke="${SIGN_WHITE}" stroke-width="3"/>${inner||''}`; }
function plate(inner){ return `<rect x="4" y="4" width="92" height="92" rx="5" fill="${SIGN_WHITE}" stroke="${SIGN_BLACK}" stroke-width="3"/>${inner||''}`; }
function arrowUp(x,y,s,fill){ return `<path transform="translate(${x} ${y}) scale(${s})" d="M0 -22 L12 -6 H5 V22 H-5 V-6 H-12 Z" fill="${fill}"/>`; }
export function bikeIcon(fill){ return `<g fill="none" stroke="${fill}" stroke-width="5" stroke-linecap="round"><circle cx="30" cy="62" r="14"/><circle cx="70" cy="62" r="14"/><path d="M30 62 L45 36 H62 L70 62 M45 36 L52 62 M40 36 H52"/></g>`; }
export function pedIcon(x,y,s,fill){ return `<g transform="translate(${x} ${y}) scale(${s})" fill="${fill}"><circle cx="0" cy="-22" r="6"/><path d="M-4 -14 H4 L8 4 L4 4 L4 22 H-1 L-1 6 L-4 22 H-9 L-6 4 L-8 -2 Z"/></g>`; }
export function carIcon(x,y,s,fill){ return `<g transform="translate(${x} ${y}) scale(${s})" fill="${fill}"><path d="M-22 6 L-16 -8 L-6 -14 H8 L18 -8 L22 6 V12 H-22 Z"/><circle cx="-12" cy="12" r="5"/><circle cx="12" cy="12" r="5"/></g>`; }
function bentLine(from, to){ // priority-plate line, 'from'/'to' in S,N,E,W ; thick black line
  const P = {S:[50,92],N:[50,8],E:[92,50],W:[8,50]};
  const a=P[from], b=P[to];
  return `<path d="M${a[0]} ${a[1]} L50 50 L${b[0]} ${b[1]}" fill="none" stroke="${SIGN_BLACK}" stroke-width="12" stroke-linejoin="round"/>`;
}
function thinArms(list){ return list.map(d=>{const P={S:[50,92],N:[50,8],E:[92,50],W:[8,50]};const a=P[d];return `<path d="M50 50 L${a[0]} ${a[1]}" stroke="${SIGN_BLACK}" stroke-width="4"/>`;}).join(''); }

export const SIGNS = {
  '205': { name:'Vorfahrt gewähren', en:'Give way', desc:'Upside-down triangle. Others go first — you may roll on without stopping if the road is clear.', svg: () => triDown(SIGN_WHITE, SIGN_RED) },
  '206': { name:'Stop', en:'Stop and give way', desc:'Come to a full stop at the line (or where you can see), then go only when clear. A "rolling stop" is a fine.', svg: () => `<path d="M30 4 H70 L96 30 V70 L70 96 H30 L4 70 V30 Z" fill="${SIGN_RED}" stroke="${SIGN_WHITE}" stroke-width="4"/><text x="50" y="60" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="28" fill="#fff">STOP</text>` },
  '301': { name:'Vorfahrt', en:'Priority at the next intersection only', desc:'You go first at the next crossing. After that, right-before-left is back unless another sign says otherwise.', svg: () => triUp() },
  '306': { name:'Vorfahrtstraße', en:'Priority road', desc:'Yellow diamond: you have priority at every crossing until sign 307 ends it. Side streets must give way to you.', svg: () => `<path d="M50 4 L96 50 L50 96 L4 50 Z" fill="${SIGN_WHITE}"/><path d="M50 16 L84 50 L50 84 L16 50 Z" fill="${SIGN_YELLOW}"/>` },
  '307': { name:'Ende der Vorfahrtstraße', en:'End of priority road', desc:'Priority road ends here. From the next crossing, right-before-left applies again unless signed.', svg: () => `<path d="M50 4 L96 50 L50 96 L4 50 Z" fill="${SIGN_WHITE}"/><path d="M50 16 L84 50 L50 84 L16 50 Z" fill="${SIGN_YELLOW}"/><path d="M20 80 L80 20 M28 88 L88 28 M12 72 L72 12" stroke="${SIGN_BLACK}" stroke-width="4"/>` },
  '102': { name:'Kreuzung mit Vorfahrt von rechts', en:'Crossing ahead — right before left', desc:'Warning: at the next crossing, whoever comes from the right goes first. Slow down and look right.', svg: () => triUp(`<path d="M50 34 V78 M30 56 H70" stroke="${SIGN_BLACK}" stroke-width="9"/>`) },
  '1002-10': { name:'Abknickende Vorfahrt (von unten nach rechts)', en:'Priority road bends right', desc:'The thick line shows where the priority road goes. If you follow the bend, you keep priority — but you must signal.', svg: () => plate(thinArms(['N']) + bentLine('S','E')) },
  '1002-20': { name:'Abknickende Vorfahrt (von unten nach links)', en:'Priority road bends left', desc:'The thick line shows where the priority road goes. Follow the bend with your indicator on; you keep priority.', svg: () => plate(thinArms(['N']) + bentLine('S','W')) },
  '1002-11': { name:'Abknickende Vorfahrt (Seitenstraße)', en:'Priority road bends, seen from the side street', desc:'You are on the thin line. The priority road runs across and bends — everything on the thick line goes before you.', svg: () => plate(thinArms(['S']) + bentLine('W','N')) },
  '215': { name:'Kreisverkehr', en:'Roundabout', desc:'Together with the give-way triangle: cars already in the roundabout go first. No indicator when entering, indicator when leaving.', svg: () => circleBlue(`<g fill="none" stroke="#fff" stroke-width="7"><path d="M50 22 A28 28 0 1 0 74 36"/><path d="M50 22 A28 28 0 0 0 26 36" /></g><path d="M70 22 L80 40 L60 40 Z" fill="#fff"/><path d="M22 60 L20 40 L36 52 Z" fill="#fff"/><path d="M52 82 L70 72 L66 88 Z" fill="#fff"/>`) },
  '220': { name:'Einbahnstraße', en:'One-way street', desc:'Traffic only flows in the arrow direction. Priority rules do not change — right-before-left still applies at unsigned crossings.', svg: () => `<rect x="2" y="26" width="96" height="48" fill="${SIGN_BLUE}" stroke="#fff" stroke-width="3"/><path d="M14 50 H70 L58 36 M70 50 L58 64" fill="none" stroke="#fff" stroke-width="8"/><text x="50" y="72" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="8" fill="#fff">Einbahnstraße</text>` },
  '209': { name:'Vorgeschriebene Fahrtrichtung rechts', en:'You must turn right', desc:'Blue circle with an arrow: the only allowed direction. Common at the end of one-way streets and side roads onto main roads.', svg: () => circleBlue(`<path d="M28 50 H66 L54 36 M66 50 L54 64" fill="none" stroke="#fff" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/>`) },
  '209-10': { name:'Vorgeschriebene Fahrtrichtung geradeaus', en:'Straight ahead only', desc:'No turning at this crossing.', svg: () => circleBlue(arrowUp(50,50,1.4,'#fff')) },
  '720': { name:'Grünpfeil', en:'Green arrow plate', desc:'Small green arrow next to the red light: you may turn right on red — but only after a full stop, and only if nobody (especially cyclists and pedestrians) is hindered.', svg: () => `<rect x="4" y="4" width="92" height="92" fill="${SIGN_BLACK}"/><path d="M22 50 H66 L52 32 M66 50 L52 68" fill="none" stroke="${SIGN_GREEN}" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>` },
  '325.1': { name:'Verkehrsberuhigter Bereich', en:'Traffic-calmed area (living street)', desc:'Walking pace only, pedestrians may use the whole street, children may play. When you leave the area you must give way to everyone.', svg: () => rectBlue(`<rect x="14" y="14" width="72" height="72" fill="#fff"/><path d="M20 44 L36 30 L52 44 Z" fill="${SIGN_BLUE}"/><rect x="24" y="44" width="24" height="18" fill="${SIGN_BLUE}"/>${carIcon(68,72,.55,SIGN_BLUE)}${pedIcon(30,76,.55,SIGN_BLUE)}${pedIcon(52,80,.4,SIGN_BLUE)}<circle cx="62" cy="40" r="5" fill="${SIGN_BLUE}"/>`) },
  '325.2': { name:'Ende des verkehrsberuhigten Bereichs', en:'End of traffic-calmed area', desc:'Leaving the living street: you have no priority. Let cars, bikes and pedestrians on the road go first.', svg: () => rectBlue(`<rect x="14" y="14" width="72" height="72" fill="#fff"/><path d="M20 44 L36 30 L52 44 Z" fill="${SIGN_BLUE}"/><rect x="24" y="44" width="24" height="18" fill="${SIGN_BLUE}"/>${carIcon(68,72,.55,SIGN_BLUE)}${pedIcon(30,76,.55,SIGN_BLUE)}<path d="M18 82 L82 18" stroke="${SIGN_RED}" stroke-width="6"/>`) },
  '274.1': { name:'Tempo-30-Zone', en:'30 km/h zone', desc:'Whole area is 30 km/h. Inside a 30 zone crossings are usually unsigned — expect right-before-left everywhere.', svg: () => plate(`<text x="50" y="30" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="16" fill="${SIGN_BLACK}">ZONE</text><circle cx="50" cy="62" r="26" fill="#fff" stroke="${SIGN_RED}" stroke-width="6"/><text x="50" y="71" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="24" fill="${SIGN_BLACK}">30</text>`) },
  '274-30': { name:'Zulässige Höchstgeschwindigkeit 30', en:'Speed limit 30 km/h', desc:'Berlin has 30 km/h on many main roads (often at night or near schools). Check the extra plate for times.', svg: () => circleRed(`<text x="50" y="64" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="40" fill="${SIGN_BLACK}">30</text>`) },
  '244.1': { name:'Fahrradstraße', en:'Bicycle street', desc:'Bicycles own the street and may ride side by side. Cars only if a plate allows it (e.g. "Anlieger frei"), max 30 km/h, and you must not push cyclists.', svg: () => plate(`<circle cx="50" cy="44" r="30" fill="${SIGN_BLUE}" stroke="#fff" stroke-width="2"/><g transform="translate(50 44) scale(.5) translate(-50 -50)">${bikeIcon('#fff')}</g><text x="50" y="88" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="11" fill="${SIGN_BLACK}">Fahrradstraße</text>`) },
  '237': { name:'Radweg', en:'Cycle path', desc:'Cyclists must use it. When you turn across it, cyclists going straight have priority — in both directions if the path is two-way.', svg: () => circleBlue(`<g transform="translate(50 50) scale(.62) translate(-50 -50)">${bikeIcon('#fff')}</g>`) },
  '224': { name:'Haltestelle', en:'Bus / tram stop', desc:'Green H on yellow. Pass a stopped bus or tram carefully; with hazard lights on, walking pace only and no overtaking while it approaches.', svg: () => `<circle cx="50" cy="50" r="46" fill="${SIGN_YELLOW}" stroke="${SIGN_GREEN}" stroke-width="5"/><text x="50" y="68" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="52" fill="${SIGN_GREEN}">H</text>` },
  '201': { name:'Andreaskreuz', en:'Railway crossing', desc:'Trains and trams on their own track always go first. Never enter if you would have to stop on the tracks.', svg: () => `<path d="M12 18 L88 82 M88 18 L12 82" stroke="${SIGN_WHITE}" stroke-width="20" stroke-linecap="round"/><path d="M12 18 L88 82 M88 18 L12 82" stroke="${SIGN_RED}" stroke-width="14" stroke-linecap="round"/><path d="M28 32 L72 68 M72 32 L28 68" stroke="#fff" stroke-width="5"/>` },
  '350': { name:'Fußgängerüberweg', en:'Zebra crossing', desc:'Pedestrians who want to cross have priority. Approach slowly, be ready to stop, and never overtake at a zebra crossing.', svg: () => rectBlue(`<path d="M22 40 L78 40 L92 84 H8 Z" fill="#fff"/><g fill="${SIGN_BLUE}"><path d="M30 42 L56 42 L64 84 H40 Z" /><path d="M64 42 L78 42 L92 84 H76 Z" /></g>${pedIcon(50,58,1,SIGN_BLACK)}`) },
  '283': { name:'Absolutes Halteverbot', en:'No stopping', desc:'Not even for a moment. Arrows on the sign show whether it applies before, after, or both.', svg: () => `<circle cx="50" cy="50" r="46" fill="${SIGN_BLUE}" stroke="${SIGN_RED}" stroke-width="9"/><path d="M22 22 L78 78 M78 22 L22 78" stroke="${SIGN_RED}" stroke-width="8"/>` },
  '286': { name:'Eingeschränktes Halteverbot', en:'No parking (stopping up to 3 min allowed)', desc:'You may stop for up to 3 minutes to load or let someone out, but not park.', svg: () => `<circle cx="50" cy="50" r="46" fill="${SIGN_BLUE}" stroke="${SIGN_RED}" stroke-width="9"/><path d="M78 22 L22 78" stroke="${SIGN_RED}" stroke-width="8"/>` },
  '314': { name:'Parken', en:'Parking', desc:'Parking allowed. Check the plate: residents (Bewohner), Parkscheibe, times, or "mit Parkschein".', svg: () => rectBlue(`<text x="50" y="72" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="62" fill="#fff">P</text>`) },
  '270.1': { name:'Umweltzone', en:'Low-emission zone', desc:'Inside the Berlin S-Bahn ring you need a green environmental sticker (Plakette) on the windscreen.', svg: () => plate(`<text x="50" y="26" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="12" fill="${SIGN_BLACK}">UMWELT</text><circle cx="50" cy="58" r="26" fill="#fff" stroke="${SIGN_RED}" stroke-width="6"/><text x="50" y="66" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="20" fill="${SIGN_BLACK}">ZONE</text>`) },
  '267': { name:'Verbot der Einfahrt', en:'No entry', desc:'Usually the other end of a one-way street. Cyclists may be allowed by a plate — expect bikes coming toward you.', svg: () => `<circle cx="50" cy="50" r="46" fill="${SIGN_RED}" stroke="#fff" stroke-width="4"/><rect x="18" y="42" width="64" height="16" fill="#fff"/>` },
  '245': { name:'Bussonderfahrstreifen', en:'Bus lane', desc:'Only buses (and often taxis, bikes — see plate). Cars may cross it to turn right, giving way to buses and cyclists in it.', svg: () => circleBlue(`<rect x="24" y="30" width="52" height="34" rx="4" fill="#fff"/><rect x="30" y="36" width="40" height="14" fill="${SIGN_BLUE}"/><circle cx="34" cy="68" r="5" fill="#fff"/><circle cx="66" cy="68" r="5" fill="#fff"/>`) },
  '1022-10': { name:'Radverkehr frei', en:'Bicycles allowed', desc:'Plate under a sign: cyclists may go where the sign forbids others. Under a no-entry sign it means bikes will come toward you.', svg: () => plate(`<g transform="translate(50 40) scale(.5) translate(-50 -50)">${bikeIcon(SIGN_BLACK)}</g><text x="50" y="84" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="16" fill="${SIGN_BLACK}">frei</text>`) },
  '1020-30': { name:'Anlieger frei', en:'Residents and visitors allowed', desc:'Only people with business on the street may drive in — but that includes visitors and deliveries.', svg: () => plate(`<text x="50" y="45" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="17" fill="${SIGN_BLACK}">Anlieger</text><text x="50" y="72" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="17" fill="${SIGN_BLACK}">frei</text>`) },
  '1000-32': { name:'Radfahrer kreuzen', en:'Cyclists cross from both sides', desc:'Plate under a warning sign: expect bikes crossing from left and right, e.g. a two-way cycle path.', svg: () => plate(`<g transform="translate(50 42) scale(.5) translate(-50 -50)">${bikeIcon(SIGN_BLACK)}</g><path d="M14 78 H86 M22 72 L14 78 L22 84 M78 72 L86 78 L78 84" fill="none" stroke="${SIGN_BLACK}" stroke-width="4"/>`) },
  '138': { name:'Radverkehr', en:'Warning: cyclists', desc:'Cyclists cross or join here. Look twice before turning.', svg: () => triUp(`<g transform="translate(50 60) scale(.42) translate(-50 -50)">${bikeIcon(SIGN_BLACK)}</g>`) },
  '136': { name:'Kinder', en:'Warning: children', desc:'School or playground nearby. Slow down, be ready to brake.', svg: () => triUp(`${pedIcon(44,60,.7,SIGN_BLACK)}${pedIcon(58,64,.5,SIGN_BLACK)}`) },
  '151': { name:'Bahnübergang', en:'Railway crossing ahead', desc:'Warning before a rail or tram crossing without barriers.', svg: () => triUp(`<path d="M32 74 H68 M36 48 L64 48 M50 40 V78" stroke="${SIGN_BLACK}" stroke-width="6"/><path d="M34 80 Q50 52 66 80" fill="none" stroke="${SIGN_BLACK}" stroke-width="5"/>`) },
  '250': { name:'Verbot für Fahrzeuge aller Art', en:'No vehicles', desc:'Closed to all vehicles unless a plate makes an exception (often "Anlieger frei" or "Radverkehr frei").', svg: () => circleRed() },
  'kfzfrei': { name:'Kfz frei', en:'Motor vehicles allowed', desc:'Plate under a bicycle-street sign: cars may use the street — as guests, at 30 km/h max.', svg: () => plate(`${carIcon(50,44,.9,SIGN_BLACK)}<text x="50" y="84" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="16" fill="${SIGN_BLACK}">frei</text>`) },
  'bewohner': { name:'Bewohner mit Parkausweis', en:'Residents with permit', desc:'Plate under a parking sign in Berlin parking zones: without a resident permit you need a ticket from the machine — or cannot park at all, depending on the plate.', svg: () => plate(`<text x="50" y="40" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="12" fill="${SIGN_BLACK}">Bewohner mit</text><text x="50" y="58" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="12" fill="${SIGN_BLACK}">Parkausweis</text><text x="50" y="80" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="12" fill="${SIGN_BLACK}">frei</text>`) },
  'parkscheibe': { name:'Parkscheibe', en:'Parking disc required', desc:'Set the blue disc to the next half hour after you arrive, place it on the dashboard. Time limit is on the plate.', svg: () => plate(`<circle cx="40" cy="44" r="22" fill="${SIGN_BLUE}"/><path d="M40 44 V26 M40 44 L52 52" stroke="#fff" stroke-width="4" stroke-linecap="round"/><text x="50" y="86" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="12" fill="${SIGN_BLACK}">2 Std.</text>`) },
};

export function signSVG(code, size, extraClass){
  const s = SIGNS[code]; if(!s) return '';
  return `<svg viewBox="0 0 100 100" width="${size||40}" height="${size||40}" class="${extraClass||''}" role="img" aria-label="${s.name}">${s.svg()}</svg>`;
}
